name: Browser-driven specification review
description: >
  If your browser is considering shipping a feature
  that hasn't had a Working Group take it through wide review,
  please use this form.
title: "Browser review: "
labels:
  - "Progress: untriaged"
  - "Review type: later review"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sending us your specification review. If a Working Group generally agrees about this feature, we prefer to have them take it through wide review. If they're willing to do that, please [switch to the WG new specification review template](https://github.com/w3ctag/design-reviews/issues/new?template=005-wg-new-spec-review.yaml). Otherwise, if you're planning to ship the feature anyway, please continue to file the review with this form.

        Use links to content rather than pasting text into this issue. Issues are ephemeral and most of the material we are asking for has long term value.

        Please preview the issue and check that the links work before submitting. Please make sure anyone with the link can access the document. We may refuse to review anything that is not public.

  - type: input
    attributes:
      label: Specification
      placeholder: Enter a URL.
      value: "https://"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other documents
      description: List any other documents that are relevant to our review.
      value: |
        - Start the review by reading: <!-- URL; especially if the spec's introduction isn't aimed at unfamiliar audiences -->
        - Explainer: <!-- Based on https://w3ctag.github.io/explainer-explainer/, minus any sections that have moved to the specification. -->
        - Web Platform Tests:
        - Previous early design review, if any: https://github.com/w3ctag/design-reviews/issues/####

  - type: checkboxes
    attributes:
      label: The specification and other documents
      options:
        - label: Include an introduction that's understandable by people who weren't familiar with the problem space.
          required: true
        - label: Describe [the problems that end-users were facing](https://w3ctag.github.io/explainer-explainer/#end-user-need) before this proposal.
          required: true
        - label: Describe the [alternatives that you considered](https://w3ctag.github.io/explainer-explainer/#alternatives).
          required: true
        - label: Give [examples of how to use the proposal to solve the end-users' problems, and what the end-users wind up experiencing](https://w3ctag.github.io/explainer-explainer/#describe-proposal).
        - label: Describe user research you did to validate the problem and/or design.
        - label: Follow the [Web Platform Design Principles](https://www.w3.org/TR/design-principles/).
        - label: Include Security and Privacy Considerations sections based on answers to the [Security/Privacy Questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/).

  - type: textarea
    attributes:
      label: Where and by whom is the work is being done?
      value: |
        - GitHub repo:
        - Primary contacts:
          - $name (@-mention), $organization/s, $role in developing specification
          - <!-- repeat as necessary, we recommend including group chairs and editors in this list -->
        - Organization/project driving the specification:
        - This work is being funded by:
        - Primary standards group developing this feature:
        - Group intended to standardize this work: <!-- if different from the current group -->
        - Incubation and standards groups that have discussed the design:
          - {{ABC CG}} <!-- Include a link to minutes or issues in this group if possible. -->
          - {{DEF WG}}

  - type: textarea
    attributes:
      label: Feedback so far
      description: |
        For your own organization, you can simply state the organization's position instead of linking to it.  This includes items on [Mozilla standards-positions](https://github.com/mozilla/standards-positions), and [WebKit standards-positions](https://github.com/WebKit/standards-positions).  Chromium doesn't have a standards-positions repository and [prefers](https://source.chromium.org/chromium/chromium/src/+/main:docs/standards/positions/GoogleChrome/README.md) to use comments from the teams that maintain the relevant area of their codebase.
      value: |
        - Multi-stakeholder feedback:
          - Chromium comments:
          - Mozilla comments: https://github.com/mozilla/standards-positions/issues/NNN <!-- And/or other places they've given feedback -->
          - WebKit comments: https://github.com/WebKit/standards-positions/issues/NNN <!-- And/or other places they've given feedback -->
          - {{...include feedback/review from developers, implementers, civil society, and others}}
        - Major unresolved issues with or opposition to this specification:
        - Status/issue trackers for implementations⁴: <!-- Include links to [Chrome Status](https://chromestatus.com/), [Mozilla's](https://bugzilla.mozilla.org/), [WebKit's Bugzilla](https://bugs.webkit.org/), and trackers for other implementations if those are known to you. -->

  - type: textarea
    attributes:
      label: You should also know that...
      description: |
        Please tell us anything else you think is relevant to this review.

        If there are time constraints on our review, describe them here.
